// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpOpqcw5jW4tNs5LZtQCW8GZGlW9Saehk',
    appId: '1:11305972540:web:8bdc2317ab447ecedca439',
    messagingSenderId: '11305972540',
    projectId: 'list-pilot',
    authDomain: 'list-pilot.firebaseapp.com',
    storageBucket: 'list-pilot.firebasestorage.app',
    measurementId: 'G-WZ668FCP8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOvbrvCe2WJcf8QDBWEzMheIH7AJHUyAE',
    appId: '1:11305972540:android:0c970d6d0a63ab43dca439',
    messagingSenderId: '11305972540',
    projectId: 'list-pilot',
    storageBucket: 'list-pilot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9YLz-LcTJATsWxb9q0NIlMUOjtr5Ktg',
    appId: '1:11305972540:ios:c2a856cde1f56e2adca439',
    messagingSenderId: '11305972540',
    projectId: 'list-pilot',
    storageBucket: 'list-pilot.firebasestorage.app',
    iosBundleId: 'com.listpilot.listPilot',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpOpqcw5jW4tNs5LZtQCW8GZGlW9Saehk',
    appId: '1:11305972540:web:2a8f2d7a87dddd04dca439',
    messagingSenderId: '11305972540',
    projectId: 'list-pilot',
    authDomain: 'list-pilot.firebaseapp.com',
    storageBucket: 'list-pilot.firebasestorage.app',
    measurementId: 'G-WZ668FCP8T',
  );
}
